services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - autostack

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    depends_on:
      - redis
    ports:
      - "5540:5540"
    networks:
      - autostack
    volumes:
      - redisinsight-data:/db
      - ./redisinsight-connections:/connections 
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379
      - RI_REDIS_PASSWORD=${REDIS_PASSWORD}
      - RI_REDIS_USER=default  
      - RI_HOST=0.0.0.0 

  mongo:
    container_name: mongo
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: autostack
    volumes:
      - mongo_data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d:ro
    networks:
      - autostack

  mongo-compass:
    container_name: mongo-compass
    image: haohanyang/compass-web
    restart: always
    ports:
      - "8081:8080"
    environment:
      CW_MONGO_URI: ${MONGO_COMPASS_URL}
      CW_BASIC_AUTH_USERNAME: ${MONGO_COMPASS_USER}
      CW_BASIC_AUTH_PASSWORD: ${MONGO_COMPASS_PASSWORD}
      
    depends_on:
      - mongo
    networks:
      - autostack

networks:
  autostack:
    driver: bridge

volumes:
  mongo_data:
  redis-data:
    driver: local
  redisinsight-data:
    driver: local