services:
  kafka:
    image: apache/kafka:latest
    container_name: autostack_broker
    hostname: broker
    ports:
      - "9092:9092"
    expose:
      - "9093"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092, PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - autostack
  
  kafka-init:
    image: apache/kafka:latest
    container_name: autostack-kafka-init
    depends_on:
      - kafka
    volumes:
      - ../kafka/scripts:/scripts
    command: > 
      bash -c "
        mkdir -p /tmp/kafka-init &&
        cp /scripts/init.sh /tmp/kafka-init &&
        chmod +x /tmp/kafka-init/init.sh &&
        /tmp/kafka-init/init.sh
      "
    networks:
      - autostack

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: autostack-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_O_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - autostack

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: autostack
    volumes:
      - mongo_data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d:ro
    networks:
      - autostack

  mongo-compass:
    container_name: mongo-compass
    image: haohanyang/compass-web
    restart: always
    ports:
      - "8081:8080"
    environment:
      CW_MONGO_URI: ${MONGO_COMPASS_URL}
      CW_BASIC_AUTH_USERNAME: ${MONGO_COMPASS_USER}
      CW_BASIC_AUTH_PASSWORD: ${MONGO_COMPASS_PASSWORD}
      
    depends_on:
      - mongo
    networks:
      - autostack

networks:
  autostack:
    driver: bridge

volumes:
  mongo_data: